name: "[CD] Continuous Delivery"

#on:
#  push:
#    breaches: [ main ]

on:
  pull_request:
    types: [ opened, synchronize ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## ====================
      - name: "Debug"
        run: "ls -lah"
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Lint"yar
        run: "npx vercel --prod"

