name: "[CD] Continuous Delivery"

#on:
#  push:
#    breaches: [ main ]

on:
  pull_request:
    types: [ opened, synchronize ]

env:
  VESEL_PROJECT_ID: prj_AuDM0GfFUpR3gzmR8rTNBe1O5F9t
  VERMICELLI_ORG_ID: team_VQFo16uoCwlC0i8ZIimDcw4J

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## ====================
      - name: "Debug"
        run: "ls -la"
      - name: "Install Dependencies"
        run: "yarn install"
      - name: "Deploy"
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
