name: "CD Continuous Delivery"

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Debug"
        run: "ls -la"

      - name: "Install Dependencies"
        run: "yarn install"

      - name: "Deploy"
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
